CREATE TABLE IF NOT EXISTS pokemon (
  id INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  sprite_url VARCHAR(500),
  stats_json JSON,
  types_json JSON,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
